name: hello reusable workflow
on:
  workflow_call:
  workflow_dispatch:
  
jobs:
  hello:
    env:
      script: ./scripts/hello.sh
    name: checkout
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          repository: 'efi-rfauzan/reusable-workflow'
          ref: 'main'
      - name: chmod
        run: chmod u+x ${{ env.script }}
      - name: hello
        run: ${{ env.script }}
      - name: Check secret is equal to PASS
        run: |
          [[ "${{ secrets.TEST_SECRET }}" == "PASS" ]] && echo "Strings are equal" || echo "Strings are not equal"
